# -*- coding: utf-8 -*-
"""Aula_IA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DCQE_zJDTyxh02p4L9YYHpuDPMusCaE0
"""

from imageai.Detection import ObjectDetection
import os

caminho = os.getcwd()

detector = ObjectDetection()
detector.setModelTypeAsYOLOv3()
detector.setModelPath(os.path.join(caminho, "yolo.h5"))
detector.loadModel()
deteccoes = detector.detectObjectsFromImage(input_image=os.path.join(caminho, "pessoas.jpg"), output_image_path=os.path.join(caminho, "imagemNovaPessoa.jpg"))

for cadaObjeto in deteccoes:
  print(cadaObjeto["name"]," : ", cadaObjeto["percentage_probability"])
  print("-----------------------------------------")